language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.0
    - android-25

before_install:
  - chmod +x gradlew

script:
  - ./gradlew clean build --info
